name: Suena
favicon: null
layout_spectrum: 0.96872
typography_spectrum: 0.30289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a7975'
    - '#644c7e'
    - '#261937'
    - '#e49ff2'
    - '#f9fdfe'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
