name: Suena
favicon: null
layout_spectrum: 0.96872
typography_spectrum: 0.30289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79fca'
    - '#ffffff'
    - '#231f20'
    - '#cdc9e1'
    - '#544f5f'
  brandStrength: 0.9957754011265934
  lightness: 0.8993882117792964
  saturation: 0.15927034080959857
  rhythmicContrast: 0.75
purpose: []
