name: Suena
favicon: null
layout_spectrum: 0.48106
typography_spectrum: 0.44859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a7975'
    - '#644c7e'
    - '#261937'
    - '#e49ff2'
    - '#f9fdfe'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
